# Part of Odoo. See COPYRIGHT & LICENSE files for full copyright and licensing details.
{
    'name': 'Sample Bag Management | Sample Inventory Control | Inventory Sample Distribution',
    'version': '17.0.0.0',
    'author': 'TechUltra Solutions Private Limited',
    'category': 'Sales',
    'website': 'https://www.techultrasolutions.com',
    "company": "TechUltra Solutions Private Limited",
    'summary': """
    This module helps businesses efficiently create, manage, and track sample bags assigned to sales representatives. The module simplifies sample distribution, inventory tracking, and sample bag management while improving visibility and control over promotional product activities.
    Sample Product Management,
    Sample Bag Management,
    Product Sample Tracking,
    Sample Product Distribution,
    Sample Inventory Management,
    Sample Product Tracker,
    Sample Distribution Management,
    Sales Sample Management,
    Sample Stock Management,
    Product Sampling System,
    Sales Sample Tracking,
    Customer Sample Management,
    Product Demonstration Management,
    Promotional Product Management,
    Marketing Sample Distribution,
    Sample Inventory Tracking,
    Sample Stock Control,
    Sample Product Movement Tracking,
    Odoo Sample Product Management,
    Odoo Sample Bag Management,
    Odoo Product Sample Tracking,
    Odoo Sample Distribution,
    Odoo Sample Inventory Management,
    Sample Request Management,
    Sample Return Management,
    Manage Sample Products in Odoo,
    Odoo Sample Bag Tracking System,
    Product Sample Distribution Management,
    Track Sample Products in Odoo,
    Advanced Sample Product Management for Odoo
    """,
    'description': """
    Sample Bag Management | Sample Inventory Control | Inventory Sample Distribution enhances Odoo's sales and inventory operations by providing a structured system for managing, tracking, and distributing sample products. The module helps businesses organize sample product requests, monitor sample allocations, and maintain complete visibility over products distributed to customers, prospects, or sales representatives.
    Sample Product Management,
    Sample Bag Management,
    Product Sample Tracking,
    Sample Product Distribution,
    Sample Inventory Management,
    Sample Product Tracker,
    Sample Distribution Management,
    Sales Sample Management,
    Sample Stock Management,
    Product Sampling System,
    Sales Sample Tracking,
    Customer Sample Management,
    Product Demonstration Management,
    Promotional Product Management,
    Marketing Sample Distribution,
    Sample Inventory Tracking,
    Sample Stock Control,
    Sample Product Movement Tracking,
    Odoo Sample Product Management,
    Odoo Sample Bag Management,
    Odoo Product Sample Tracking,
    Odoo Sample Distribution,
    Odoo Sample Inventory Management,
    Sample Request Management,
    Sample Return Management,
    Manage Sample Products in Odoo,
    Odoo Sample Bag Tracking System,
    Product Sample Distribution Management,
    Track Sample Products in Odoo,
    Advanced Sample Product Management for Odoo
    """,
    'depends': ['sale_management','sale','stock','sale_stock','product','l10n_in_sale_stock'],
    "data": [
        "security/ir.model.access.csv",
        "data/sample_bag_sequence.xml",
        "wizard/salesperson_update_views.xml",
        "wizard/sample_bag_create_so_views.xml",
        "wizard/sample_bag_from_so_views.xml",
        "wizard/scrap_quantity.xml",
        "wizard/warehouse_transfer_from_sb_views.xml",
        "views/sample_bag_views.xml",
        "views/sale_order_views_inherit.xml",
        "views/stock_warehouse_views_inherit.xml",
        "views/stock_picking_views_inherit.xml",
        "views/product_product_inherit_views.xml",
        "views/res_config_settings_inherit.xml",
    ],
    'images': [
        'static/description/main_screen.gif',
    ],
    'price': 29.01,
    'currency': 'USD',
    'installable': True,
    'auto_install': False,
    'license': 'OPL-1',
    "application": False,
}
