# -*- coding: utf-8 -*-
# Part of Odoo. See COPYRIGHT & LICENSE files for full copyright and licensing details.
{
    'name': 'Odoo JSON RPC | Custom API Integration | Odoo External API Connector',
    'version': '19.0.0.0',
    'category': 'Extra Tools',
    'summary': """
    This module enables external systems to access Odoo records and execute standard or custom Odoo methods through JSON-based requests, providing a flexible and efficient solution for system integration and data exchange.
    Odoo JSON API,
    Odoo API Integration,
    Odoo REST API,
    Odoo JSON API Connector,
    Odoo API Access,
    Odoo Custom API,
    Odoo Integration API,
    JSON API for Odoo,
    Odoo API Framework,
    Odoo Data Integration,
    Odoo API Connector,
    Odoo Third-Party Integration,
    Odoo External API,
    Odoo System Integration,
    JSON API Integration,
    JSON RPC Odoo,
    JSON Data Exchange,
    Odoo Developer API,
    Odoo Custom Method API,
    Odoo API Development,
    ERP API Integration,
    CRM API Integration,
    Mobile App Odoo Integration,
    Website Odoo Integration,
    Odoo Automation API,
    Odoo Data Synchronization,
    Odoo JSON API Integration,
    Odoo Custom API Integration,
    Execute Custom Methods Through Odoo API,
    Advanced JSON API for Odoo
    """,
    'description': """
    Odoo JSON RPC | Custom API Integration | Odoo External API Connector provides a flexible and efficient way to access, create, update, and manage Odoo records through JSON-based API requests. In addition to supporting Odoo's built-in methods, the module also allows developers to execute custom methods created within Odoo, offering greater flexibility for advanced business requirements. By leveraging JSON, organizations can achieve faster integrations, streamlined data processing, and seamless connectivity between Odoo and external platforms while maintaining a structured and scalable API architecture.    
    Odoo JSON API,
    Odoo API Integration,
    Odoo REST API,
    Odoo JSON API Connector,
    Odoo API Access,
    Odoo Custom API,
    Odoo Integration API,
    JSON API for Odoo,
    Odoo API Framework,
    Odoo Data Integration,
    Odoo API Connector,
    Odoo Third-Party Integration,
    Odoo External API,
    Odoo System Integration,
    JSON API Integration,
    JSON RPC Odoo,
    JSON Data Exchange,
    Odoo Developer API,
    Odoo Custom Method API,
    Odoo API Development,
    ERP API Integration,
    CRM API Integration,
    Mobile App Odoo Integration,
    Website Odoo Integration,
    Odoo Automation API,
    Odoo Data Synchronization,
    Odoo JSON API Integration,
    Odoo Custom API Integration,
    Execute Custom Methods Through Odoo API,
    Advanced JSON API for Odoo
    """,
    'author': 'TechUltra Solutions Private Limited',
    'company': 'TechUltra Solutions Private Limited',
    'website': 'https://www.techultrasolutions.com/',
    'depends': ['base', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/token.xml',
    ],
    "images": [
        "static/description/main_screen.gif",
    ],
    'price': 49.00,
    'currency': 'USD',
    'installable': True,
    'auto_install': False,
    "license": "OPL-1",
    "application": False,
}
