# Part of Odoo. See COPYRIGHT & LICENSE files for full copyright and licensing details.
{
    'name': 'Invoice & Payment ZIP Export | Password-Protected Document Archive',
    'version': '19.0.0.0',
    'author': 'TechUltra Solutions Private Limited',
    'category': 'tool',
    'website': 'https://www.techultrasolutions.com',
    "company": "TechUltra Solutions Private Limited",
    'summary': """
    Invoice & Payment ZIP Export | Password-Protected Document Archive enables users to export multiple invoices, vendor bills, credit notes, and payment reports into a single ZIP archive with optional password protection, simplifying secure document sharing, storage, and bulk accounting report management.
    Invoice ZIP Export,
    Payment Report ZIP Export,
    Accounting Document ZIP Export,
    Financial Report ZIP Export,
    Password Protected ZIP Export,
    Invoice Report Export,
    Payment Report Export,
    Secure Document Export,
    Accounting Report Archive,
    Financial Document Archive,
    Odoo Invoice Export,
    Odoo Payment Report Export,
    Odoo ZIP Export,
    Odoo Accounting Report Export,
    Odoo Financial Document Export,
    Odoo Invoice ZIP Download,
    Odoo Payment ZIP Export,
    Odoo Password Protected Reports,
    Customer Invoice Export,
    Vendor Bill Export,
    Customer Credit Note Export,
    Vendor Credit Note Export,
    Password Protected Invoice Export,
    Secure Financial Report Export,
    Bulk Invoice Export,
    Multiple Report ZIP Export,
    Export Multiple Invoices to ZIP in Odoo,
    Odoo Invoice ZIP Export with Password Protection,
    Odoo QWeb Report ZIP Export,
    Secure Accounting Report Distribution
    """,
    'description': """
    Invoice & Payment ZIP Export | Password-Protected Document Archive enhances Odoo's document management capabilities by allowing users to export multiple QWeb reports into a single ZIP archive with optional password protection. The module streamlines bulk document handling by consolidating invoices, vendor bills, credit notes, payments, and other supported QWeb-generated reports into one compressed file for convenient storage, sharing, and distribution.
    Invoice ZIP Export,
    Payment Report ZIP Export,
    Accounting Document ZIP Export,
    Financial Report ZIP Export,
    Password Protected ZIP Export,
    Invoice Report Export,
    Payment Report Export,
    Secure Document Export,
    Accounting Report Archive,
    Financial Document Archive,
    Odoo Invoice Export,
    Odoo Payment Report Export,
    Odoo ZIP Export,
    Odoo Accounting Report Export,
    Odoo Financial Document Export,
    Odoo Invoice ZIP Download,
    Odoo Payment ZIP Export,
    Odoo Password Protected Reports,
    Customer Invoice Export,
    Vendor Bill Export,
    Customer Credit Note Export,
    Vendor Credit Note Export,
    Password Protected Invoice Export,
    Secure Financial Report Export,
    Bulk Invoice Export,
    Multiple Report ZIP Export,
    Export Multiple Invoices to ZIP in Odoo,
    Odoo Invoice ZIP Export with Password Protection,
    Odoo QWeb Report ZIP Export,
    Secure Accounting Report Distribution
    """,
    'depends': ['account'],
    'data': [
        'security/ir.model.access.csv',
        'security/res_groups_view.xml',
        'views/account_move.xml',
        'wizard/export_accounting_wizard.xml',
    ],
    'images': [
        'static/description/main_screen.gif',
    ],
    'price': 14.85,
    'currency': 'USD',
    'installable': True,
    'auto_install': False,
    'license': 'OPL-1',
    "application": False,
}
