# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    "name": "AI Odoo Website Product Image Search | Machine Learning & Artificial Intelligence for eCommerce | Image-Based Shopping Solutions",
    "version": "19.0.0.0",
    "category": "Website",
    "author": "TechUltra Solutions Private Limited",
    "company": "TechUltra Solutions Private Limited",
    "website": "www.techultrasolutions.com",
    "summary": """
        Welcome to the next generation of product discovery on Odoo! With this module, users can search products using images instead of typing text. Simply upload a product image, and the AI will intelligently scan and match it with existing product photos from your store, displaying visually similar items instantly. It’s fast, intuitive, and ideal for industries like fashion, furniture, electronics, and more — where visual appearance matters most.
        AI-Powered Visual Search for Odoo Website,
        AI Odoo Website Product Image Search,
        Machine Learning & Artificial Intelligence for eCommerce,
        Image-Based Shopping Solutions,
        AI Image Search,
        Odoo eCommerce,
        Product Discovery,
        Machine Learning,
        Image-Based Shopping,
        Visual Search,
        Artificial Intelligence,
        Odoo Module,
        Smart Shopping,
        Image Recognition,
        Odoo Product Search,
        eCommerce Solutions,
        User  Experience,
        Online Shopping,
        Image Upload Search,
    """,
    "description": """
        Welcome to the next generation of product discovery on Odoo! With this module, users can search products using images instead of typing text. Simply upload a product image, and the AI will intelligently scan and match it with existing product photos from your store, displaying visually similar items instantly. It’s fast, intuitive, and ideal for industries like fashion, furniture, electronics, and more — where visual appearance matters most.
        AI-Powered Visual Search for Odoo Website,
        AI Odoo Website Product Image Search,
        Machine Learning & Artificial Intelligence for eCommerce,
        Image-Based Shopping Solutions,
        AI Image Search,
        Odoo eCommerce,
        Product Discovery,
        Machine Learning,
        Image-Based Shopping,
        Visual Search,
        Artificial Intelligence,
        Odoo Module,
        Smart Shopping,
        Image Recognition,
        Odoo Product Search,
        eCommerce Solutions,
        User  Experience,
        Online Shopping,
        Image Upload Search,
    """,
    "depends": ["website_sale"],
    "external_dependencies": {
        'python': ['tensorflow',
                   'Pillow'
                   ]
    },
    "data": [
        "security/ir.model.access.csv",
        "views/res_config_settings_views.xml",
        "views/website_sale_template_inherit.xml",
        "views/product_image_embedding_views.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "ai_odoo_website_product_image_search/static/src/css/image_search.scss",
            "ai_odoo_website_product_image_search/static/src/xml/image_search_dialog.xml",
            "ai_odoo_website_product_image_search/static/src/js/image_search_popup.js",
            "ai_odoo_website_product_image_search/static/src/js/image_search.js",
        ],
    },
    "images": ["static/description/main_screen.gif"],
    "license": "OPL-1",
    "installable": True,
    "application": True,
    "auto_install": False,
    "price": 99,
    "currency": "USD",
}
