# Part of Odoo. See COPYRIGHT & LICENSE files for full copyright and licensing details.
{
    'name': 'Attachment ZIP Download | Bulk Attachment Archive Manager',
    'version': '16.0.0.0',
    'category': 'Tools',
    'summary': """
    Create and download ZIP archives from multiple record attachments, making document organization, sharing, and file management more efficient.
    Attachment ZIP Download,
    Bulk Attachment Archive Manager,
    Attachment ZIP Generator,
    ZIP File Creation,
    Attachment Archive Download,
    Document ZIP Download,
    Bulk Attachment Download,
    ZIP Archive Generator,
    Attachment Export Tool,
    File Archive Manager,
    Odoo Attachment ZIP Download,
    Odoo ZIP Generator,
    Odoo Attachment Export,
    Odoo Document Archive,
    Odoo Attachment Management,
    Attachment Archive Management,
    Document Archive Manager,
    Document ZIP Export,
    Multiple Attachment Download,
    ZIP Archive Creation,
    Bulk ZIP Download,
    Automatic ZIP Download,
    Server Action ZIP Generator,
    ZIP Creation via Server Action,
    Attachment ZIP Automation,
    Generate ZIP File from Attachments in Odoo,
    Download Multiple Attachments as ZIP,
    Bulk Attachment Export to ZIP,
    Create ZIP from Record Attachments,
    Universal Attachment ZIP Creator
    """,
    'description': """
    Attachment ZIP Download | Bulk Attachment Archive Manager enables users to generate and download ZIP archives directly from record attachments, simplifying document sharing, storage, and bulk file management.
    Attachment ZIP Download,
    Bulk Attachment Archive Manager,
    Attachment ZIP Generator,
    ZIP File Creation,
    Attachment Archive Download,
    Document ZIP Download,
    Bulk Attachment Download,
    ZIP Archive Generator,
    Attachment Export Tool,
    File Archive Manager,
    Odoo Attachment ZIP Download,
    Odoo ZIP Generator,
    Odoo Attachment Export,
    Odoo Document Archive,
    Odoo Attachment Management,
    Attachment Archive Management,
    Document Archive Manager,
    Document ZIP Export,
    Multiple Attachment Download,
    ZIP Archive Creation,
    Bulk ZIP Download,
    Automatic ZIP Download,
    Server Action ZIP Generator,
    ZIP Creation via Server Action,
    Attachment ZIP Automation,
    Generate ZIP File from Attachments in Odoo,
    Download Multiple Attachments as ZIP,
    Bulk Attachment Export to ZIP,
    Create ZIP from Record Attachments,
    Universal Attachment ZIP Creator
    """,
    'author': 'TechUltra Solutions Private Limited',
    'company': 'TechUltra Solutions Private Limited',
    'website': 'https://www.techultrasolutions.com/',
    'depends': ['base'],
    "data": [
        "views/ir_actions_server.xml",
    ],
    "demo": ["demo/attachment.xml"],
    "images": [
        "static/description/main_screen.gif",
    ],
    'price': 12.82,
    'currency': 'USD',
    'installable': True,
    'auto_install': False,
    "license": "OPL-1",
    "application": False,
}
