# Part of Odoo. See COPYRIGHT & LICENSE files for full copyright and licensing details.
{
    'name': 'Inventory Delivery Report ZIP Export | Encrypted Report ZIP Secure',
    'version': '17.0.0.0',
    'author': 'TechUltra Solutions Private Limited',
    'category': 'Operations',
    'website': 'https://www.techultrasolutions.com',
    "company": "TechUltra Solutions Private Limited",
    'summary': """
    Invoice Report ZIP Export enables users to export multiple delivery slips and receipt reports into a single ZIP file with optional password protection. The module simplifies secure document distribution, bulk report management, and protected access to business documents.
    Receipt ZIP Export,
    Delivery ZIP Export,
    Password Protected ZIP Export,
    Receipt and Delivery Export,
    Secure Document Export,
    ZIP Archive Export,
    Bulk Report Export,
    Protected Document Archive,
    Delivery Report Export,
    Receipt Report Export,
    Odoo Receipt Export,
    Odoo Delivery Export,
    Odoo ZIP Export,
    Odoo Password Protected Reports,
    Odoo Delivery Report Export,
    Odoo Receipt Report Export,
    Odoo Report ZIP Download,
    Secure ZIP Archive,
    Encrypted Document Export,
    Protected Report Export,
    Secure Report Distribution,
    Password Protected Reports,
    Bulk Receipt Export,
    Bulk Delivery Export,
    Multi Report Export,
    Export Delivery Reports to ZIP in Odoo,
    Export Receipt Reports to ZIP in Odoo,
    Odoo ZIP Export with Password Protection,
    Delivery Slip ZIP Export,
    Receipt Report ZIP Export
    """,
    'description': """
    Invoice Report ZIP Export | Encrypted Report ZIP Secure enhances Odoo's document distribution process by allowing users to export multiple delivery slips and receipts into a single ZIP archive with optional password protection. The module simplifies bulk document handling by consolidating multiple reports into one compressed file, making document sharing, delivery, and storage more efficient.
    Receipt ZIP Export,
    Delivery ZIP Export,
    Password Protected ZIP Export,
    Receipt and Delivery Export,
    Secure Document Export,
    ZIP Archive Export,
    Bulk Report Export,
    Protected Document Archive,
    Delivery Report Export,
    Receipt Report Export,
    Odoo Receipt Export,
    Odoo Delivery Export,
    Odoo ZIP Export,
    Odoo Password Protected Reports,
    Odoo Delivery Report Export,
    Odoo Receipt Report Export,
    Odoo Report ZIP Download,
    Secure ZIP Archive,
    Encrypted Document Export,
    Protected Report Export,
    Secure Report Distribution,
    Password Protected Reports,
    Bulk Receipt Export,
    Bulk Delivery Export,
    Multi Report Export,
    Export Delivery Reports to ZIP in Odoo,
    Export Receipt Reports to ZIP in Odoo,
    Odoo ZIP Export with Password Protection,
    Delivery Slip ZIP Export,
    Receipt Report ZIP Export
    """,
    'depends': ['stock'],
    'data': [
        'security/ir.model.access.csv',
        'security/res_groups_view.xml',
        'views/stock_delivery.xml',
        'wizard/export_delivery_wizard.xml',
    ],
    'images': [
        'static/description/main_screen.gif',
    ],
    'price': 14.85,
    'currency': 'USD',
    'installable': True,
    'auto_install': False,
    'license': 'OPL-1',
    "application": False,
}
