# Part of Techultra Solutions. See LICENSE file for full copyright and licensing details.
# -*- coding: utf-8 -*-
import base64
from io import BytesIO

from odoo import api, fields, models
from odoo.exceptions import ValidationError


class StockCardWizard(models.TransientModel):
    _name = "stock.card.wizard"
    _description = "Stock Card Report Wizard"

    date_from = fields.Date(required=True)
    date_to = fields.Date(required=True)

    warehouse_id = fields.Many2one("stock.warehouse", string="Warehouse")
    location_id = fields.Many2one("stock.location", string="Location", domain=[("usage", "in", ("internal", "view"))])

    group_by = fields.Selection(
        [("product", "Product"), ("category", "Category")],
        default="product",
        required=True,
    )

    product_ids = fields.Many2many("product.product", string="Products")
    category_id = fields.Many2one("product.category", string="Category")

    output_format = fields.Selection(
        [("pdf", "PDF"), ("xlsx", "Excel")],
        default="pdf",
        required=True,
    )

    @api.constrains("date_from", "date_to")
    def _check_dates(self):
        for rec in self:
            if rec.date_from and rec.date_to and rec.date_from > rec.date_to:
                raise ValidationError("From Date must be earlier than To Date.")

    def action_print(self):
        self.ensure_one()
        if self.output_format == "xlsx":
            return self.action_export_xlsx()

        data = {"wizard_id": self.id}
        return self.env.ref("inventory_stock_card_report.action_stock_card_report_pdf").report_action(self, data=data)

    def action_export_xlsx(self):
        self.ensure_one()
        try:
            import xlsxwriter
        except Exception as e:
            raise ValidationError("xlsxwriter is required on the server to export Excel.")

        engine = self.env["inventory.stock.card.engine"]
        payload = engine.get_report_data(self)

        output = BytesIO()
        workbook = xlsxwriter.Workbook(output, {"in_memory": True})
        sheet = workbook.add_worksheet("Stock Card")

        title = workbook.add_format({"bold": True,'bg_color': '#ABE0F0', 'align': 'center' })
        center = workbook.add_format({'align': 'center'})
        herder = workbook.add_format({"bold": True,'bg_color': '#E0E0E0','align': 'center'})
        date_fmt = workbook.add_format({"num_format": "yyyy-mm-dd",'align': 'center'})
        num_fmt = workbook.add_format({"num_format": "#,##0.00",})
        total_fmt = workbook.add_format({"num_format": "#,##0.00",'bg_color': '#E0E0E0'})

        r = 0
        h = payload["header"]
        r +=1
        sheet.write(r, 2, "STOCK CARD REPORT", title)
        r += 2
        sheet.write(r, 0, "Warehouse", herder)
        sheet.write(r, 1, "Location", herder)
        sheet.write(r, 2, "From", herder)
        sheet.write(r, 3, "To", herder)
        sheet.write(r, 4, "Generated By", herder)
        r+=1
        sheet.write(r, 0, h["warehouse"],center)
        # sheet.write(r, 1, "Location", bold)
        sheet.write(r, 1, h["location"],center)
        # r += 1
        # sheet.write(r, 0, "From", bold)
        sheet.write_datetime(r, 2, fields.Datetime.to_datetime(h["date_from"]), date_fmt)
        # sheet.write(r, 3, "To", bold)
        sheet.write_datetime(r, 3, fields.Datetime.to_datetime(h["date_to"]), date_fmt)
        # r += 1
        # sheet.write(r, 0, "Generated By", bold)
        sheet.write(r, 4, h["generated_by"], center)
        r += 2

        # Table headers
        if self.group_by == "category":
            sheet.write(r, 0, "Group", herder)
            sheet.write(r, 1, "Product", herder)
            sheet.write(r, 2, "Date", herder)
            sheet.write(r, 3, "Origin", herder)
            sheet.write(r, 4, "In Qty", herder)
            sheet.write(r, 5, "Out Qty", herder)
            sheet.write(r, 6, "Balance", herder)
            r += 1
        else:
            sheet.write(r, 0, "Product", herder)
            sheet.write(r, 1, "Date", herder)
            sheet.write(r, 2, "Origin", herder)
            sheet.write(r, 3, "In Qty", herder)
            sheet.write(r, 4, "Out Qty", herder)
            sheet.write(r, 5, "Balance", herder)
            r += 1

        for g in payload["groups"]:
            for line in g["lines"]:
                if self.group_by == 'category':
                    sheet.write(r, 0, g["title"], center)
                    sheet.write(r, 1, line['product'], center)
                    sheet.write_datetime(r, 2, fields.Datetime.to_datetime(line["date"]), date_fmt)
                    sheet.write(r, 3, line["origin"] or "", center)
                    sheet.write_number(r, 4, line["in_qty"] or 0.0, num_fmt)
                    sheet.write_number(r, 5, line["out_qty"] or 0.0, num_fmt)
                    sheet.write_number(r, 6, line["balance"] or 0.0, num_fmt)
                    r += 1
                else:
                    sheet.write(r, 0, g["title"], center)
                    sheet.write_datetime(r, 1, fields.Datetime.to_datetime(line["date"]), date_fmt)
                    sheet.write(r, 2, line["origin"] or "", center)
                    sheet.write_number(r, 3, line["in_qty"] or 0.0, num_fmt)
                    sheet.write_number(r, 4, line["out_qty"] or 0.0, num_fmt)
                    sheet.write_number(r, 5, line["balance"] or 0.0, num_fmt)
                    r += 1

            # Totals row
            if self.group_by == 'category':
                sheet.write(r, 3, "TOTAL", herder)
                sheet.write_number(r, 4, g["totals"]["in_qty"], total_fmt)
                sheet.write_number(r, 5, g["totals"]["out_qty"], total_fmt)
                r += 2
            else:
                sheet.write(r, 2, "TOTAL", herder)
                sheet.write_number(r, 3, g["totals"]["in_qty"], total_fmt)
                sheet.write_number(r, 4, g["totals"]["out_qty"], total_fmt)
                r += 2

        sheet.set_column(0, 0, 30)
        sheet.set_column(1, 1, 12)
        sheet.set_column(2, 2, 40)
        sheet.set_column(3, 5, 14)

        workbook.close()
        output.seek(0)

        filename = "Stock_Card_Report.xlsx"
        attachment = self.env["ir.attachment"].create(
            {
                "name": filename,
                "type": "binary",
                "datas": base64.b64encode(output.read()),
                "res_model": self._name,
                "res_id": self.id,
                "mimetype": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            }
        )

        return {
            "type": "ir.actions.act_url",
            "url": f"/web/content/{attachment.id}?download=true",
            "target": "self",
        }