# Part of Odoo. See COPYRIGHT & LICENSE files for full copyright and licensing details.
{
    'name': 'POS Fixed Amount Discount | Order Line Discount Management | POS Individual Product Discount',
    'version': '19.0.0.0',
    'author': 'TechUltra Solutions Private Limited',
    'category': 'Point of Sale',
    'website': 'https://www.techultrasolutions.com',
    "company": "TechUltra Solutions Private Limited",
    'summary': """
    POS Fixed Amount Discount enables businesses to apply precise monetary discounts to individual POS order lines, providing greater flexibility than percentage-based discounts. The module ensures accurate real-time calculations, transparent pricing, and seamless discount management during sales transactions.
    POS Fixed Amount Discount,
    POS Fixed Discount,
    POS Order Line Discount,
    POS Line Item Discount,
    POS Product Discount,
    Fixed Amount Discount in POS,
    POS Flat Discount,
    POS Discount Management,
    POS Discount Control,
    Odoo POS Fixed Discount,
    Odoo POS Discount Management,
    Odoo POS Order Line Discount,
    Odoo POS Product Discount,
    Odoo POS Fixed Amount Discount,
    Odoo Point of Sale Discount,
    Fixed Discount per Product,
    Line-Level Discount Management,
    Product Wise Discount,
    Item Wise Discount,
    Monetary Discount Management,
    POS Promotional Discounts,
    POS Customer Discounts,
    POS Sales Promotions,
    POS Price Reduction,
    Apply Fixed Discount on POS Order Lines,
    Fixed Amount Discount in Odoo POS,
    POS Product Wise Fixed Discount,
    POS Discount by Fixed Amount,
    Fixed Discount for Individual Products,
    POS Product Discount Control
    """,
    'description': """
    POS Fixed Amount Discount | Order Line Discount Management | POS Individual Product Discount enhances Odoo Point of Sale by enabling users to apply fixed monetary discounts directly to individual order lines. Unlike standard percentage-based discounts, the module allows businesses to specify an exact discount amount for each product, providing greater flexibility in pricing, promotions, and customer-specific discount strategies.
    POS Fixed Amount Discount,
    POS Fixed Discount,
    POS Order Line Discount,
    POS Line Item Discount,
    POS Product Discount,
    Fixed Amount Discount in POS,
    POS Flat Discount,
    POS Discount Management,
    POS Discount Control,
    Odoo POS Fixed Discount,
    Odoo POS Discount Management,
    Odoo POS Order Line Discount,
    Odoo POS Product Discount,
    Odoo POS Fixed Amount Discount,
    Odoo Point of Sale Discount,
    Fixed Discount per Product,
    Line-Level Discount Management,
    Product Wise Discount,
    Item Wise Discount,
    Monetary Discount Management,
    POS Promotional Discounts,
    POS Customer Discounts,
    POS Sales Promotions,
    POS Price Reduction,
    Apply Fixed Discount on POS Order Lines,
    Fixed Amount Discount in Odoo POS,
    POS Product Wise Fixed Discount,
    POS Discount by Fixed Amount,
    Fixed Discount for Individual Products,
    POS Product Discount Control
    """,
    'depends': ['point_of_sale'],
    'data': [
        'views/pos_order_view.xml',
        'views/res_config_settings.xml',
    ],
    'assets': {
        'point_of_sale.assets_prod': [
            'pos_orderline_fix_amount_discount/static/src/overrides/main.js',
            'pos_orderline_fix_amount_discount/static/src/control_buttons/fix_discount_btn.xml',
            'pos_orderline_fix_amount_discount/static/src/overrides/OrderLine.xml',
            'pos_orderline_fix_amount_discount/static/src/overrides/ticket_screen.js',
            'pos_orderline_fix_amount_discount/static/src/control_buttons/fix_discount_btn.js',
        ],
    },
    'images': [
        'static/description/main_screen.gif',
    ],
    'price': 19.96,
    'currency': 'USD',
    'installable': True,
    'auto_install': False,
    'license': 'OPL-1',
    "application": False,
}
